baseURL = "https://modest-varahamihira-bf4d1e.netlify.app/"
languageCode = "en-us"
theme = "hyde"
title = "My New Hugo Site"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-08"
